export const ADD_MESSAGES = 'ADD_MESSAGES'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const ADD_TODO = 'ADD_TODO'
export const CHANGESECOND = 'CHANGE_SECOND'

// 获取message页面的数据
export const CHANGINGMESSAGELIST = 'CHANGING_MESSAGE_LIST'
export const CHANGEDMESSAGELIST = 'CHANGEDMESSAGELIST'
export const CHANGEfAILED = 'CHANGEfAILED'
export const CHANGECOUNTER = 'CHANGECOUNTER'
/****************** */

// 发现页面
export const GETHISTORYTODAY = 'GETHISTORYTODAY'
export const GETHISTORYTODAYFAILED = 'GETHISTORYTODAYFAILED'
export const GETHISTORYTODAYSUCCESS = 'GETHISTORYTODAYSUCCESS'
// ********************